'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:c5a83970-8530-47cb-92cb-c19d012306e7',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'messageboardv-hosting-mobilehub-1073162058',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3ij8opzbwrvs4.cloudfront.net',
    'aws_mobile_analytics_app_id': '4d5f3916541d4b53a67727fa5bdb45b4',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'b1803b0b-4e09-44d8-8094-1f739e9d6e3c',
    'aws_project_name': 'message-board-v-1',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'messageboardv-mobilehub-1073162058'
};

exports.default = awsmobile;